sudo: required
services:
  - docker
before_install:
  - echo DATABASE_URL=postgres://vorleser@postgres/vorleser > .env
  - docker build -t vorleser-server .
  - docker pull postgres:latest
script:
  - docker-compose up -d
  - docker-compose run app bash -c "diesel setup && cargo test"
