services:
  - docker
before_install:
  - docker pull hatzel/vorleser-test
script:
  - docker run -v $(pwd):/root/code -w /root/code -i hatzel/vorleser-test cargo tarpaulin
cache:
  directories:
    - target
