services:
  - docker
before_install:
  - docker pull hatzel/vorleser-test
script:
  - docker-compose up -d
  - docker-compose run app bash -c "diesel setup && cargo test"
cache:
  directories:
    - target
