services:
  - docker
before_install:
  - docker pull hatzel/vorleser-test
script:
  - docker run -v $(pwd):/vorleser -w /vorleser -i hatzel/vorleser-test cargo test
cache:
  directories:
    - target
