[package]
authors = ["Lukas Stabe <ahti333@gmail.com>", "Hans Ole Hatzel <hhatzel@gmail.com>"]
name = "vorleser-rust"
version = "0.1.0"

[dependencies]
argon2rs = "0.2"
base64 = "~0.6.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "*"
dotenv = "*"
diesel = { version = "0.16", features = ["postgres", "uuid", "chrono", "serde_json"] }
diesel_codegen = { version = "0.15", features = ["postgres"] }
env_logger = "*"
error-chain = "0.11.0"
ffmpeg-sys = { version = "3.2.0", features = ["avformat"], default-features = false }
humanesort = "0.1.0-alpha"
image = "0.12.3"
lazy_static = "0.2"
libc = "0.2"
log = "*"
mime-sniffer = "0.1.1"
r2d2 = "0.7.1"
r2d2-diesel = "0.16"
regex = "0.2.1"
ring = "0.12"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git"  }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", features = ["json", "uuid"], default-features = false }
serde = "1"
serde_derive = "1"
serde_json = "1"
uuid = { version = "0.5", features = ["use_std", "serde", "v4"] }
validator = "0.4"
validator_derive = "0.5"
walkdir = "1"

[dev-dependencies]
stainless = { git = "https://github.com/neverfox/stainless", branch="feature/ast-item-tokens" }
