[package]
name = "vorleser-rust"
version = "0.1.0"
authors = ["Hans Ole Hatzel <hhatzel@gmail.com>"]

[dependencies]
ffmpeg-sys = { git = "https://github.com/hatzel/rust-ffmpeg-sys.git" }
libc = "0.2"
