[package]
authors = [
    "Lukas Stabe <ahti333@gmail.com>",
    "Hans Ole Hatzel <hhatzel@gmail.com>",
]
name = "vorleser-rust"
version = "0.1.0"

[[bin]]
name = "vorleser_server_bin"
path = "src/bin/main.rs"

[dependencies]
argon2rs = "0.2"
base64 = "~0.6.0"
clap = "*"
dotenv = "*"
env_logger = "*"
error-chain = "0.11.0"
humanesort = "0.1.0-alpha"
image = "0.12.3"
lazy_static = "0.2"
libc = "0.2"
log = "*"
r2d2 = "0.7.1"
r2d2-diesel = "0.16"
regex = "0.2.1"
ring = "0.12"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.4.5"
validator = "0.4"
validator_derive = "0.5"
walkdir = "1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.diesel]
features = [
    "postgres",
    "uuid",
    "chrono",
    "serde_json",
]
version = "0.16"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.15"

[dependencies.ffmpeg-sys]
default-features = false
features = ["avformat"]
version = "3.3.3"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket.git"

[dependencies.rocket_codegen]
git = "https://github.com/SergioBenitez/Rocket.git"

[dependencies.rocket_contrib]
default-features = false
features = [
    "json",
    "uuid",
]
git = "https://github.com/SergioBenitez/Rocket.git"

[dependencies.uuid]
features = [
    "use_std",
    "serde",
    "v4",
]
version = "0.5"
[dev-dependencies.stainless]
git = "https://github.com/reem/stainless"

[lib]
name = "vorleser_server"
path = "src/lib.rs"
