[package]
authors = ["Lukas Stabe <ahti333@gmail.com>", "Hans Ole Hatzel <hhatzel@gmail.com>"]
name = "vorleser-rust"
version = "0.1.0"
[dependencies]
argon2rs = "0.2"
clap = "*"
dotenv = "0.8.0"
log = "*"
env_logger = "*"
image = "0.12.3"
lazy_static = "0.2"
libc = "0.2"
quick-error = "*"
r2d2 = "0.7.1"
r2d2-diesel = "0.11"
regex = "0.2.1"
ring = "0.9.5"
rocket = "0.2.*"
rocket_codegen = "0.2.*"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
validator = "0.4"
validator_derive = "0.4"
walkdir = "1"
humanesort = "0.1.0-alpha"
error-chain = "0.10.0"

[dependencies.chrono]
features = ["serde"]
version = "0.3"

[dependencies.diesel]
features = ["postgres", "uuid", "chrono", "serde_json"]
version = "0.11"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.11"

[dependencies.ffmpeg-sys]
default-features = false
features = ["avformat"]
version = "3.2.0"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
version = "0.2.*"

[dependencies.uuid]
features = ["use_std", "serde", "v4"]
version = "0.4"
