database = "data/vorleser.sqlite"
data_directory = "data"
register_web = false

[scan]
enabled = true
interval = 600

[logging]
file = "lol.log"
level = "info"

[web]
address = "localhost"
port = 8000
